import type { Metadata } from "next";
import { Space_Grotesk } from 'next/font/google';
import '../lib/fontawesome';
import '@/app/globals.css'
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-space-grotesk',
  display: 'swap', // Added display: 'swap' for better FOUT handling
});

export const metadata: Metadata = {
  title: "Mark Alber - Full Stack Developer",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} antialiased`}
      >
        {children}

      </body>
    </html>
  );
}
